      totalItems += '<div class="cart-item-compitence--title">';
      totalItems += '<h4 class="h4">'+cartData[items][3]+'<h4>';
      totalItems += '</div>';
      totalItems += '<div class="cart-item-compitence--ink"><div class="cart-item-compitence--ink-title">';
      totalItems += '<h5 class="h5"><span>'+cartData[items][2]+':</span> Выявляет зоны неэффективности в собственной работе</h5>';
      totalItems += '</div>';
      totalItems += '<div class="cart-item-compitence--ink-item"><div class="cart-item-compitence--tabs">';
      totalItems += '<div class="compitence--tabs-tl">';
      totalItems += '<span>'+cartData[items][1]+'%:</span> '+cartData[items][4];
      totalItems += '</div>';
      totalItems += '<ul>';
      totalItems += '<li><a href="#">В течение года выявить зоны неэффективности... </a></li>';
      totalItems += '</ul>';
      totalItems += '</div></div>';
      totalItems += '</div>';